"""Domain models public API."""

from adaptive_rag.domain.models.confidence import ConfidenceBreakdown, ConfidenceScore
from adaptive_rag.domain.models.conversation import Message, MessageRole
from adaptive_rag.domain.models.decomposition import (
    DecompositionResult,
    SubQuery,
    SubQueryResult,
    SubQueryRetrievalPlan,
    SubQuerySource,
)
from adaptive_rag.domain.models.document import Chunk, Document
from adaptive_rag.domain.models.grounding import (
    AnswerMode,
    Citation,
    CitationReport,
    CitationValidation,
    ClaimSupport,
    GroundingReport,
    GuardDecision,
    GuardResult,
)
from adaptive_rag.domain.models.index import (
    CollectionStats,
    FilterStrategy,
    IndexMetadata,
    SparseBackend,
    SparseRetrieverCapabilities,
    VectorBackend,
    VectorQuery,
    VectorRecord,
    VectorStoreCapabilities,
)
from adaptive_rag.domain.models.query import (
    ComplexityLevel,
    DecompositionDecision,
    QueryAnalysis,
    QueryIntent,
    QueryType,
    OriginalQueryAnalysis,
    ResolvedQueryAnalysis,
    EffectiveQueryAnalysis,
    RetrievalDecision,
    RewriteDecision,
    RewriteResult,
)
from adaptive_rag.domain.models.retrieval import (
    RetrievalStrategy,
    ScoredChunk,
    SearchScope,
    SubqueryState,
    SubquerySummary,
)
from adaptive_rag.domain.models.trace import RetrievalTrace, StepTrace

__all__ = [
    "AnswerMode",
    "Chunk",
    "Citation",
    "CitationReport",
    "CitationValidation",
    "ClaimSupport",
    "CollectionStats",
    "ComplexityLevel",
    "ConfidenceBreakdown",
    "ConfidenceScore",
    "DecompositionDecision",
    "DecompositionResult",
    "Document",
    "FilterStrategy",
    "GroundingReport",
    "GuardDecision",
    "GuardResult",
    "IndexMetadata",
    "Message",
    "MessageRole",
    "QueryAnalysis",
    "QueryIntent",
    "QueryType",
    "OriginalQueryAnalysis",
    "ResolvedQueryAnalysis",
    "EffectiveQueryAnalysis",
    "RewriteDecision",
    "RewriteResult",
    "RetrievalDecision",
    "RetrievalTrace",
    "ScoredChunk",
    "SearchScope",
    "SparseBackend",
    "SparseRetrieverCapabilities",
    "StepTrace",
    "SubQuery",
    "SubQueryResult",
    "SubQueryRetrievalPlan",
    "SubQuerySource",
    "SubqueryState",
    "SubquerySummary",
    "VectorBackend",
    "VectorQuery",
    "VectorRecord",
    "VectorStoreCapabilities",
]
